### ISSUE TITLE
Namespace conflict ApnServer::Server::EM

### ISSUE THREAD

**Issue by jnak** [bpoweski/apnserver#5]
Hi,

I've just upgraded to 0.2 and I'm facing a weird issue issue both on my dev and prod machines. When running apnserverd, I get : 

"../lib/apnserver/server.rb:6:in `initialize': uninitialized constant ApnServer::Server::EM (NameError)"

This seems to say that when you call EM::Queue.new, it is appending this to the namespace it's in (module : ApnServer and class:Server). I can't figure out why... 

Thanks for this gem and your help !
julien

**Comment by bpoweski** [comment]
I moved around the requires to try and make event machine not a requirement, I probably broke it in the process. Are you launching it via the apnserverd script?  Try and add:

``` ruby
gem 'event_machine'
require 'event_machine'
```

To the script to see if that solves the issue

**Comment by bpoweski** [comment]
Actually, omit the underbars in those statements as it seems 'event_machine' is pointed to an older version

**Comment by jnak** [comment]
Sorry, I was away from my laptop this weekend.
I just changed inserted :

`require 'eventmachine'`

in lib/apnserver/apnserver.rb (line 1) and it worked. 
Thanks for your help !
